# Generated by Django 3.2.4 on 2022-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_auto_20220621_1007'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='legacypoliza',
            constraint=models.UniqueConstraint(fields=('legacy_poliza_expediente', 'legacy_poliza_fecha', 'legacy_poliza_numero', 'legacy_poliza_aseguradora', 'legacy_poliza_receptor'), name='legacy_poliza-constraint'),
        ),
    ]
