# Generated by Django 3.2.4 on 2022-06-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_auto_20220621_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_financiamiento',
            field=models.CharField(choices=[('N', 'Nación'), ('P', 'Provincia'), ('T', 'Terceros')], default='N', max_length=1, verbose_name='Financiamiento'),
        ),
    ]
