# Generated by Django 3.2.4 on 2022-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0006_auto_20220621_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_total_pesos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total Pesos'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_contrato_total_uvi',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto Total UVI'),
        ),
    ]
