# Generated by Django 3.2.4 on 2022-06-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_auto_20220623_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='certificado_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha DateField'),
        ),
    ]
