# Generated by Django 3.2.4 on 2022-06-30 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0008_auto_20220628_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='obra_obra_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 8, 1, 2, 1767), verbose_name='Fecha DateField'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_periodo',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Periodo'),
        ),
    ]
