# Generated by Django 3.2.4 on 2022-07-01 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0009_auto_20220630_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_fecha',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 8, 1, 2, 1767), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto en UVI'),
        ),
    ]
