# Generated by Django 3.2.4 on 2021-09-02 12:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_nombre', models.CharField(max_length=60, verbose_name='Nombre/s:')),
                ('agente_apellido', models.CharField(max_length=60, verbose_name='Apellido/s:')),
                ('agente_dni', models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='DNI:')),
                ('agente_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono:')),
                ('agente_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('agente_profesion', models.CharField(blank=True, choices=[('A', 'Arquitecto'), ('IC', 'Ingeniero Civil'), ('IE', 'Ingeniero Electromecánico'), ('MO', 'Maestro Mayor de Obras')], default=None, max_length=2, null=True, verbose_name='Profesion')),
                ('agente_matricula', models.CharField(blank=True, max_length=10, null=True, verbose_name='Matricula Profesional')),
            ],
            options={
                'verbose_name_plural': 'Agentes',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nombre', models.CharField(max_length=50, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora_nombre', models.CharField(max_length=255, verbose_name='Nombre Empresa Aeguradora')),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('departamento_nombre', models.TextField(verbose_name='Nombre Departamento')),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
                'ordering': ['departamento_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(max_length=255, verbose_name='Nombre Empresa Tomadora:')),
                ('empresa_cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT:')),
                ('empresa_titular', models.CharField(blank=True, max_length=140, null=True, verbose_name='Titular de la Empresa')),
                ('empresa_direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('localidad_nombre', models.TextField(verbose_name='Nombre Localidad')),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('localidad_centroide_lat', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True)),
                ('localidad_centroide_lon', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True)),
                ('localidad_funcion', models.CharField(blank=True, max_length=40, null=True)),
                ('localidad_departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='carga.departamento')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['localidad_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa_nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Progrma',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptor_nombre', models.CharField(max_length=100, verbose_name='Receptor')),
            ],
            options={
                'verbose_name': 'Receptor',
                'verbose_name_plural': 'Receptores',
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poliza_fecha', models.DateField(verbose_name='Fecha')),
                ('poliza_expediente', models.CharField(max_length=17, verbose_name='Número de Expediente')),
                ('poliza_numero', models.IntegerField(verbose_name='Número de Póliza')),
                ('poliza_concepto', models.CharField(choices=[('C', 'Garantía de Ejecución de Contrato'), ('F', 'Garantía de Sustitución de Fondo de Reparo'), ('A', 'Garantía de Anticipo Financiero')], max_length=1, verbose_name='Concepto')),
                ('poliza_anexo', models.CharField(blank=True, max_length=40, null=True, verbose_name='Anexo de póliza')),
                ('poliza_recibo', models.CharField(max_length=100, verbose_name='Número de Recibo')),
                ('poliza_obra_nombre', models.TextField(verbose_name='Obra')),
                ('poliza_obra_convenio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Convenio')),
                ('poliza_obra_expediente', models.CharField(blank=True, max_length=17, null=True, verbose_name='Número de Expediente de la Obra')),
                ('poliza_monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Sustituido Pesos')),
                ('poliza_monto_uvi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto Sustituido UVI')),
                ('poliza_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.area')),
                ('poliza_aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.aseguradora')),
                ('poliza_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poliza_editor', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poliza_editor', to=settings.AUTH_USER_MODEL)),
                ('poliza_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.receptor')),
                ('poliza_tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra_nombre', models.TextField(verbose_name='Nombre de la Obra tal como figura en el contrato')),
                ('obra_soluciones', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Cantidad de soluciones')),
                ('obra_grupo', models.CharField(blank=True, max_length=4, null=True, verbose_name='Grupo')),
                ('obra_plazo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Plazo de Ejecución')),
                ('obra_convenio', models.CharField(blank=True, max_length=60, null=True, verbose_name='Convenio/ACU')),
                ('obra_expediente', models.CharField(max_length=17, verbose_name='Expediente')),
                ('obra_resolucion', models.CharField(blank=True, max_length=15, null=True, verbose_name='Resolución de Adjudicación')),
                ('obra_licitacion_tipo', models.CharField(blank=True, choices=[('L', 'Licitación Pública'), ('P', 'Licitación Privada'), ('C', 'Concurso de Precios'), ('D', 'Contratación Directa')], max_length=1, null=True, verbose_name='Compulsa')),
                ('obra_licitacion_numero', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Número de Licitación')),
                ('obra_licitacion_ano', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año de Licitación')),
                ('obra_nomenclatura', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenclatura Catastral')),
                ('obra_nomenclatura_plano', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número de Plano')),
                ('obra_fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega de la Obra')),
                ('obra_fecha_contrato', models.DateField(blank=True, null=True, verbose_name='Fecha de Firma de Contrato')),
                ('obra_expediente_costo', models.CharField(blank=True, max_length=17, null=True, verbose_name='Expediente de Costos')),
                ('obra_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Empresa')),
                ('obra_inspector', models.ManyToManyField(related_name='obra_inspector', to='carga.Agente')),
                ('obra_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.localidad')),
                ('obra_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa')),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('municipio_nombre', models.CharField(max_length=40)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('municipio_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.departamento')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
                'ordering': ['municipio_nombre'],
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='localidad_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.municipio'),
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_rubro_obra', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Obra N°')),
                ('certificado_rubro_anticipo', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Anticipo N°')),
                ('certificado_rubro_devanticipo', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Devolución de Anticipo N°')),
                ('certificado_rubro_691', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Redeterminación Decreto N°691/16 N°')),
                ('certificado_rubro_Terreno', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Terreno | Cuota N°')),
                ('certificado_rubro_recomposicion', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Certificado de Recomposición Período Anterior N°')),
                ('certificado_expediente', models.CharField(max_length=17, verbose_name='Número de Expediente')),
                ('certificado_fecha', models.DateField(verbose_name='Fecha de Salida')),
                ('certificado_monto_pesos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto en UVI')),
                ('certificado_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa')),
                ('certificado_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.localidad')),
                ('certificado_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra')),
                ('certificado_programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.programa')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('poliza_fecha', 'poliza_numero', 'poliza_aseguradora', 'poliza_receptor'), name='poliza-constraint'),
        ),
    ]
