# Generated by Django 3.2.4 on 2021-07-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='poliza',
            name='poliza-constraint',
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('poliza_fecha', 'poliza_numero', 'poliza_aseguradora', 'poliza_receptor'), name='poliza-constraint'),
        ),
    ]
