# Generated by Django 3.2.4 on 2021-06-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poliza',
            options={'permissions': (('puede_editar', 'Puede editar entradas'),), 'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
    ]
