# Generated by Django 3.2.4 on 2021-08-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_alter_poliza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poliza',
            options={'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('poliza_numero', 'poliza_aseguradora', 'poliza_receptor'), name='poliza-constraint'),
        ),
    ]
