# Generated by Django 3.2.4 on 2021-08-09 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_auto_20210716_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto en UVI'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_monto_pesos',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido Pesos'),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='poliza_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Sustituido UVI'),
        ),
    ]
