# Generated by Django 3.2.4 on 2021-09-03 14:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='empresa_titular',
            new_name='empresa_titular_nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_correo_p',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Primaria:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_correo_s',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Dirección de Correo Alternativa:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_inscripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Inscripción:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_titular_dni',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='DNI:'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='empresa_titular_titulo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Titulo Representante:'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_conjunto',
            field=models.TextField(blank=True, null=True, verbose_name='Conjunto Licitado:'),
        ),
        migrations.AddField(
            model_name='obra',
            name='obra_observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones:'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_nacion_pesos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos: ')),
                ('contrato_nacion_uvi', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI: ')),
                ('contrato_provincia_pesos', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos: ')),
                ('contrato_provincia_uvi', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI: ')),
                ('contrato_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.obra')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
