# Generated by Django 3.2.4 on 2021-09-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_auto_20210903_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prototipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototipo_tipo', models.CharField(choices=[('1', '1 Dormitorio'), ('2', '2 Dormitorios'), ('3', '3 Dormitorios'), ('4', '4 Dormitorios'), ('o', 'Otro')], max_length=1, verbose_name='Tipo de Prototipo:')),
                ('prototipo_cantidad', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Cantidad del Prototipo:')),
                ('prototipo_superficie', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Superficie del Prototipo: ')),
                ('prototipo_uvi', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='UVIs x M2:')),
                ('prototipo_incremento', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Incremento Porcentual por Infraestructura:')),
                ('prototipo_discapacitado', models.BooleanField(default=False, verbose_name='Es Prototipo para Discapacitado: ')),
                ('prototipo_obra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carga.obra')),
            ],
        ),
    ]
