# Generated by Django 3.2.4 on 2021-09-09 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0005_prototipohabitacional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='certificado_rubro_Terreno',
            new_name='certificado_rubro_terreno',
        ),
        migrations.AddField(
            model_name='certificado',
            name='certificado_monto_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto en UVI'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_nacion_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Nación: '),
        ),
        migrations.AddField(
            model_name='contrato',
            name='contrato_provincia_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Provicia: '),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto en Pesos'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_nacion_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos: '),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_nacion_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI: '),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_provincia_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos: '),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato_provincia_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI: '),
        ),
    ]
