# Generated by Django 3.2.4 on 2021-09-09 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0007_auto_20210909_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='contrato_nacion_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en Pesos: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='contrato_nacion_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Nación en UVI: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='contrato_nacion_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Nación: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='contrato_provincia_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en Pesos: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='contrato_provincia_uvi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Provincia en UVI: '),
        ),
        migrations.AddField(
            model_name='obra',
            name='contrato_provincia_uvi_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha UVI Provicia: '),
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
    ]
