# Generated by Django 3.2.4 on 2021-09-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0008_auto_20210909_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='contrato_nacion_pesos',
            new_name='obra_contrato_nacion_pesos',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='contrato_nacion_uvi',
            new_name='obra_contrato_nacion_uvi',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='contrato_nacion_uvi_fecha',
            new_name='obra_contrato_nacion_uvi_fecha',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='contrato_provincia_pesos',
            new_name='obra_contrato_provincia_pesos',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='contrato_provincia_uvi',
            new_name='obra_contrato_provincia_uvi',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='contrato_provincia_uvi_fecha',
            new_name='obra_contrato_provincia_uvi_fecha',
        ),
    ]
