# Generated by Django 3.2.4 on 2021-10-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0009_auto_20210910_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_691',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Decreto N°691/16 N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_anticipo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_devanticipo',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Devolución de Anticipo N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_obra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Obra N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_recomposicion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Recomposición N°'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_rubro_terreno',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Terreno | Cuota N°'),
        ),
    ]
