# Generated by Django 3.2.4 on 2021-10-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0012_merge_0003_auto_20210901_1105_0011_auto_20211009_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='obra_nomenclatura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomenclatura Catastral'),
        ),
    ]
