# Generated by Django 3.2.4 on 2022-02-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0014_auto_20220201_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_fecha',
        ),
    ]
