# Generated by Django 3.2.4 on 2022-02-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0015_remove_certificado_certificado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_devolucion_expte',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Número de Expediente Devolución'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_cobrar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto a Cobrar'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_periodo',
            field=models.DateField(verbose_name='Periodo'),
        ),
    ]
