# Generated by Django 3.2.4 on 2022-02-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0016_auto_20220203_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_periodo',
            field=models.CharField(max_length=13, verbose_name='Periodo'),
        ),
    ]
