# Generated by Django 3.2.4 on 2022-02-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0017_alter_certificado_certificado_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado_devolucion_monto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto Devolución en Pesos'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_cobrar',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Monto a Cobrar'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='certificado_monto_pesos',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Monto en Pesos'),
        ),
    ]
