# Generated by Django 3.2.4 on 2022-02-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0018_auto_20220207_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_empresa',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_localidad',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_programa',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_rubro_691',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_rubro_recomposicion',
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='certificado_rubro_terreno',
        ),
        migrations.AlterField(
            model_name='obra',
            name='obra_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carga.empresa', verbose_name='Obra_Empresa'),
        ),
    ]
